var element = document.querySelector("trix-editor");
var whichSave = "";

$(function() {
  // Handler for .ready() called.
  $('.modal-trigger').leanModal();
  $('select').material_select();
  //if (bowser.webkit) {
  // do stuff with safari & chrome & opera & android & blackberry & webos & silk
  Materialize.toast('All set, Begin Writing!', 1000);
  //$( ".button_groups").prepend("<span class=\"button_group\"><button type=\"button\" onclick=\"insertHorizontalLine()\" class=\"hr\" title=\"Horizantal Line\">hr</button></span>");
  element.editor.loadJSON(JSON.parse(localStorage["editorState"]));
  //}
  //else {
  //  $('#modalBrowser').openModal();
  //}
});

function insertHTML(){
  //alert(document.getElementById("trix-input-1").value);
  //document.getElementById("textareaMarkdown").value = toMarkdown(document.getElementById("trix-input-1").value) ;
  var EditorContent = document.getElementById("trix-input-1").value;
  console.log(EditorContent);
  //var toOutput = toMarkdown(EditorContent, { gfm: true });
  //var temp;
  //temp = toOutput.replace(/<div>/g," ");
  //console.log(temp);
  
  //Replace All DIVs
  //temp = toOutput.replace(/<\/?(b|div)>/g,"");
  
  //temp = temp.replace(/<\/?(b|br)>/g,"");
  
  //document.getElementById("outputHolder").value = temp;
  //console.log(document.getElementById("outputHolder").value);
  //document.getElementById("textareaMarkdown").innerHTML = temp;
  //console.log(temp);
}
function saveAsMARKDOWNDummy(){
  $('#modalSaveMARKDOWN').openModal();
  document.getElementById('filename-html').value = "";
  whichSave = "MARKDOWN";
}

function saveAsMARKDOWN(){
  var fileNameToSaveAs;
  var textToWrite = toMarkdown(document.getElementById("trix-input-1").value, { gfm: true });
  textToWrite = textToWrite.replace(/<\/?(b|div)>/g,"");
  
  if (document.getElementById('filename-markdown').value !== ""){
    fileNameToSaveAs = document.getElementById('filename-markdown').value + ".md" ;
  }
  else
  fileNameToSaveAs = "baciPADFile.md";
  
  var mdFileAsBlob = new Blob([textToWrite], {type:'text/plain;charset=utf-8'});
  saveAs(mdFileAsBlob, fileNameToSaveAs);
}

function saveAsHTMLDummy(){
  $('#modalSaveHTML').openModal();
  document.getElementById('filename-html').value = "";
  whichSave = "HTML";
}

function saveAsHTML(){
  //alert("Save as HTML");
  /* OLD code before FileSaver.js
  var preHTML = "<!DOCTYPE html><html><title>Generated by BasicPad!</title><xmp theme=\"united\" style=\"display:none;\">";
  var postHTML = "</xmp><script src=\"http://strapdownjs.com/v/0.2/strapdown.js\"></script></html>";
  var fileNameToSaveAs;
  var textToWrite = preHTML.concat(document.getElementById("trix-input-1").value).concat(postHTML);
  var textFileAsBlob = new Blob([textToWrite], {type:'text/plain;charset=utf-8'});
  if (document.getElementById('filename-html').value !== ""){
    fileNameToSaveAs = document.getElementById('filename-html').value + ".html" ;
  }
  else
  fileNameToSaveAs = "baciPADFile.html";

  var downloadLink = document.createElement("a");
  downloadLink.download = fileNameToSaveAs;
  downloadLink.innerHTML = "Download File";
  if (window.webkitURL !== null)
    {
      downloadLink.href = window.webkitURL.createObjectURL(textFileAsBlob);
    }
  downloadLink.click(); */
  
  var themeElement = document.getElementById("theme");
  var selectedTheme = themeElement.options[themeElement.selectedIndex].value;
  
  var preHTML1 = "<!DOCTYPE html><html><title>Generated by BasicPad!</title><xmp theme=\"";
  var preHTML2 = "\" style=\"display:none;\">";
  var postHTML = "</xmp><script src=\"http://strapdownjs.com/v/0.2/strapdown.js\"></script></html>";
  var fileNameToSaveAs;
  var markdownMidFile = toMarkdown(document.getElementById("trix-input-1").value, { gfm: true });
  markdownMidFile = markdownMidFile.replace(/<\/?(b|div)>/g,"");
  
  var textToWrite = preHTML1.concat(selectedTheme).concat(preHTML2).concat(document.getElementById("trix-input-1").value).concat(postHTML);
  
  if (document.getElementById('filename-html').value !== ""){
    fileNameToSaveAs = document.getElementById('filename-html').value + ".html" ;
  }
  else
  fileNameToSaveAs = "baciPADFile.html";
  
  var htmlFileAsBlob = new Blob([textToWrite], {type:'text/plain;charset=utf-8'});
  saveAs(htmlFileAsBlob, fileNameToSaveAs);
}

function saveAsTEXTDummy(){
  whichSave = "TEXT";
}

function saveAsTEXT(){
  alert("Save as TEXT");
}

function clearAll(){
  alert("I am in!");
}

function insertHorizontalLine(){
  alert(element.editor.getSelectedRange());
  element.editor.insertString("<strong>Hello</strong>");
}

function cancelCommand(){
  if (whichSave == "HTML")
    $('#modalSaveHTML').closeModal();
  else if (whichSave == "MARKDOWN")
    $('#modalSaveMARKDOWN').closeModal();
  else if (whichSave == "TEXT")
    $('#modalSaveTEXT').closeModal();
  
  whichSave = "";
}

window.onbeforeunload = function (e) {
    e = e || window.event;

    // For IE and Firefox prior to version 4
    if (e) {
        //e.returnValue = 'Sure?';
        localStorage["editorState"] = JSON.stringify(element.editor);
    }
};
